
# Como utilizar essa publicação {- #como-utilizar}  



Este documento atende à Resolução CONAMA nº 462, de 24 de julho de 2014, que atribui ao Instituto Chico Mendes de Conservação da Biodiversidade - ICMBio a  responsabilidade pela publicação de um relatório apresentando as áreas regulares de rota, pouso, descanso, alimentação e reprodução de aves migratórias. Estas áreas, aqui tratadas por “Áreas de Concentração de Aves Migratórias”, estão representadas na Figura 7.10 e os seus respectivos arquivos com sua localização geográfica precisa estão [disponíveis para *download* em formato *.shp](https://drive.google.com/file/d/1bnLY2-kQKBWzBFrw7x2Vh4sis72jmRVS/view?usp=sharing). Este relatório também pode ser encontrado no [Portal do ICMBio](https://www.gov.br/icmbio/pt-br/centrais-de-conteudo/publicacoes/relatorios) na *internet* e no [painel *on-line*](https://cemave-sede.github.io/painel4/) criado especificamente para o compartilhamento de seu conteúdo. As áreas representadas estão sujeitas às obrigações legais estabelecidas pela resolução acima citada.  

As Áreas de Concentração de Aves Migratórias foram apontadas pela priorização espacial de locais com registros de aves migratórias realizada por meio do *software* Zonation, sendo complementadas pelos registros de literatura ou comunicação pessoal por especialistas de áreas de expressiva agregação de indivíduos. Vale ressalvar que o mapeamento realizado não contemplou o ambiente marinho e as lagunas costeiras, de modo que os resultados apresentados não representam todas as áreas importantes para aves migratórias no país.  

O modelo produzido é um indicativo, para os órgãos licenciadores, de áreas que devem receber especial atenção quando da elaboração de estudos vinculados ao licenciamento ambiental de empreendimentos eólicos. Contudo, como será discutido adiante, existem ainda diversas lacunas de conhecimento acerca da interação das aves migratórias com esse tipo de empreendimento e esse documento não esgota o assunto.  

Estudos prévios à instalação de empreendimentos em áreas não representadas na Figura 7.10, mesmo que simplificados, são necessários  para se avaliar *in loco* a ocorrência de espécies migratórias, pois este relatório não contempla informações detalhadas sobre migração de aves para todo o país em nível local.  

Além das Áreas de Concentração de Aves Migratórias, como preconizado na Resolução CONAMA nº 462/14, esta publicação traz também alguns temas associados.  É apresentado um mapa com as áreas de ocorrência de espécies de aves ameaçadas (Figura 3.3), com base em compilação realizada pelo CEMAVE a partir de registros de diferentes bancos de dados. O arquivo com essas áreas está [disponível para *download* no formato *.shp](https://drive.google.com/file/d/1bnLY2-kQKBWzBFrw7x2Vh4sis72jmRVS/view?usp=sharing). Tendo em vista que morcegos são animais bastante impactados por empreendimentos eólicos, foi também realizada uma análise da relação desse grupo com os empreendimentos eólicos *onshore*. Todos os resultados aqui apresentados têm como base a lista oficial de espécies ameaçadas de extinção, conforme a Portaria MMA nº 444/2014. Uma nova lista foi publicada recentemente pela Portaria MMA nº 148/2022 e deverá ser considerada quando da revisão do presente documento. Por fim, é oferecido ao leitor um capítulo com uma visão geral sobre complexos eólicos *offshore*. Buscou-se, assim, fornecer aos empreendedores e órgãos licenciadores informações especializadas e atualizadas que contribuam para compatibilizar os interesses socioeconômicos e ambientais na geração e distribuição de energia eólica no Brasil.