
# Apresentação {- #apresentacao}  

O Brasil é um país megadiverso que abriga mais de 13% da riqueza de espécies do globo. É o terceiro país em número de espécies de aves. Das 1.919 espécies atualmente registradas pelo Comitê Brasileiro de Registros Ornitológicos, pouco mais de 10% são atualmente definidas como migratórias, mas este número ainda pode aumentar conforme cresça o conhecimento sobre o grupo.  

Ao longo de sua rota migratória, as aves utilizam diversas áreas para descanso e alimentação. Sem essas áreas, as aves não são capazes de atingir o destino final, deixando de completar seu ciclo de vida. Algumas espécies migratórias têm suas rotas restritas ao território nacional; outras  deslocam-se por diversos países vizinhos; outras possuem uma área de distribuição que pode se estender de polo a polo. Essa interconexão notável entre ambientes, biomas, países, continentes e hemisférios executada pelas espécies migratórias torna o Brasil co-responsável frente ao compromisso de
conservação da biodiversidade.  

Como esperado, o Brasil é signatário de acordos internacionais relacionados à proteção de espécies migratórias e dos habitats por elas utilizados, como a Convenção internacional para Conservação da Fauna, Flora e Belezas Cênicas das Américas (Convenção de Washington), que trata de espécies migratórias em um dos seus capítulos; a Convenção de Ramsar, relativa à conservação de ambientes aquáticos; a Rede Hemisférica de Reservas para Aves Limícolas (aves que buscam alimento nas zonas entre marés, em ambientes alagados ou em áreas marginais a corpos d’água); o Acordo Internacional para a Conservação de Albatrozes e Petréis – ACAP; o Memorando de Entendimento para a Conservação de Espécies de Aves Migratórias dos Campos Naturais da América do Sul e de seus habitats; a Convenção de Bonn ou Convenção sobre a Conservação das Espécies Migratórias de Animais Silvestres (CMS).  

Apesar de todos esses instrumentos voltados para a conservação das espécies migratórias, há uma redução drástica e muitas vezes irreversível de suas áreas críticas de alimentação, reprodução e descanso. Mesmo quando a área crítica não é perdida por completo, ela pode vir a sofrer tal degradação ambiental que seu uso pelas espécies migratórias mais sensíveis se torna inviável. Neste sentido, é importante reconhecer estas áreas críticas e envidar esforços para o uso sustentável desses espaços e seus recursos.  

A implatação de parques eólicos têm contribuído cada vez mais para a formação de uma matriz energética brasileira mais limpa e renovável. A geração de energia a partir dos ventos é considerada de baixo impacto ao meio ambiente, mas pode representar uma ameaça a grupos específicos como aves e morcegos. Nessa perspectiva, o Conselho Nacional de Meio Ambiente (CONAMA) publicou a Resolução n° 462, de 24 de julho de 2014, estabelecendo os procedimentos para o licenciamento ambiental de empreendimentos de geração de energia elétrica a partir de fonte eólica em superfície terrestre (onshore), no território brasileiro. Essa resolução prevê que o órgão licenciador deve exigir estudos e relatório de impacto ambiental e realizar audiências públicas quando o empreendimento estiver localizado em áreas de concentração ou rota de aves migratórias, aqui chamadas de Áreas Importantes para Aves, cabendo ao ICMBio/CEMAVE indicá-las, em território nacional, por meio de um relatório, sendo essa sua terceira edição.

A sua elaboração, a exemplo das edições anteriores, foi baseada nos dados e informações disponíveis na literatura científica, em bancos de dados abertos, no processo de avaliação do estado de conservação da avifauna brasileira, nos Planos de Ação Nacionais e nos registros de anilhamento do Sistema Nacional de Anilhamento de Aves Silvestres (SNA). Contudo, o modo de priorização espacial foi aprimorado: houve redução da malha da grade de análise e uso de um software de priorização espacial, que permite considerar a riqueza de cada local e a raridade e vulnerabilidade de cada espécie.  

Com o intuito de minimizar potenciais impactos negativos, também são apresentadas recomendações de medidas preventivas ou operacionais já testadas em outros países. Da mesma forma que os relatórios anteriores, este também apresenta o mapa de registros de espécies de aves ameaçadas de extinção, que poderá ser utilizado como referência pelos órgãos licenciadores.  

De forma inédita e suplementar, esta publicação também traz informações sobre a fauna de morcegos no Brasil e o risco de colisão modelado deste grupo com estruturas associadas a empreendimentos eólicos. Tal contribuição foi possível graças a boa vontade de pesquisadores da Universidade Federal de Pernambuco e busca levar aos empreendedores e aos órgãos licenciadores a melhor informação sobre o impacto de empreendimentos eólicos nesse grupo tão essencial para os processos ecossistêmicos.  

Esse documento alinha-se ao modelo de desenvolvimento responsável, sinalizando a necessidade e a possibilidade de se permitir o crescimento econômico e social sem negligenciar a conservação da biodiversidade.

# Como utilizar essa publicação {- #como-utilizar}  

A função primordial deste relatório é atender à Resolução Conama nº 462, de 24 de julho de 2014, que indica o Instituto Chico Mendes de Conservação da Biodiversidade - ICMBio como responsável pela publicação de relatório que indique áreas regulares de rota, pousio, descanso, alimentação e reprodução de aves migratórias.  

Estas áreas estão indicadas na Figura \@ref(fig:02) (para todo o Brasil) e nas Figuras 2.1 a 2.27 (a mesma informação com foco em cada Estado). Os arquivos shapefiles dessas figuras podem ser encontrados no Portal do ICMBio na Internet. Para estas áreas,
aplica-se a obrigação legal posta pela Resolução acima citada.  

Vale ressalvar que o método utilizado no planejamento espacial que resultou nessas áreas considera a sensibilidade das espécies migratórias a empreendimentos eólicos onshore, ou seja, a figura não representa todas as áreas importantes para aves migratórias no país, em qualquer situação. Esse produto é resultado de uma pergunta específica sobre empreendimentos eólicos onshore, não devendo ser considerado como resposta para qualquer pergunta relativa a áreas importantes para aves migratórias no Brasil.  

O modelo produzido é um indicativo para os órgãos licenciadores de áreas em que deve haver especial atenção quando da elaboração de estudos de impacto ambiental. Contudo, como será discutido mais adiante, existem ainda diversas lacunas de conhecimento, de modo que esse documento não esgota o assunto. Estudos de impacto, mesmo que simplificados em áreas não assinaladas no modelo, precisam avaliar a ocorrência de espécies migratórias, in loco, pois trata-se de um nível de detalhamento da informação que escapa a essa publicação.  

Em vista da atribuição institucional do ICMBio/CEMAVE de compilar dados para a avaliação do estado de conservação da avifauna, existe neste Centro um grande volume de registros de ocorrência de espécies ameaçadas. A Resolução Conama nº 462 prevê que não será considerado de baixo impacto os empreendimentos eólicos que estejam localizados em áreas de ocorrência de espécies ameaçadas de extinção. No intuito de auxiliar empreendedores e órgãos licenciadores, apresentamos as áreas com registro de espécies de aves ameaçadas (Figura \@ref(fig:03)).  

Há também detalhamento sobre espécies endêmicas de morcegos e áreas de maior riqueza do grupo. Tendo em vista que morcegos e aves são os animais mais impactados por empreendimentos eólicos, visamos manter informações direcionadas e atualizadas sobre esses dois grupos, em um mesmo documento, de modo a apoiar o trabalho de órgãos licenciadores e empreendedores em compatibilizar interesses socioeconômicos e ambientais.